<a href="https://colab.research.google.com/github/muzibamhanif3-jpg/NUMPY-ASSIGNMENT/blob/main/NUMPY_TASKS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# **>NUMPY-ASSIGNMENT**



In [ ]:
#TASK 01: CREATE THE ARRAY:
10, 20 , 30, 40, 50

import numpy as np
arr = np.array ([10, 20, 30, 40, 50])
print(arr)
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))




[10 20 30 40 50]
150
30.0
50
10


In [ ]:
#TASK 02: GRATER THAN OR EQUAL TO 50:

import numpy as np
marks = np.array([45, 80, 30, 90, 55, 20])
print(marks[marks >= 50])
print(marks[marks <= 50])






[80 90 55]
[45 30 20]


In [ ]:
#TASK 03:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#task 04:

import numpy as np
arr = np.random.randint(40, 101, size=10)
print("marks:", arr)

print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

marks: [78 52 67 75 93 88 49 92 79 97]
77.0
97
49


In [ ]:
#TASK 05:

import numpy as np
marks = np.array([35, 67, 89, 45, 90, 22, 70, 58])
passed = marks[marks >= 50]
print(passed)
print(len(passed))
failed = marks[marks <= 50]
print(failed)
print(len(failed))


[67 89 90 70 58]
5
[35 45 22]
3


# **#practice core opertaions 1 till 17:**

In [ ]:
1. #IMPORT NUMPY:

import numpy as np

2. #phython list vs numpy array:

import numpy as np
marks = np.array([50, 60, 70 ,80])
print(marks)
print(marks + 5)


[50 60 70 80]
[55 65 75 85]


In [ ]:
3. #CREATING NUMPY ARRAYS:
#ONE DIMENSIONAL ARRAY:

import numpy as np
marks = np.array([50, 60, 70 ,80])
print(marks)

#TWO_DIMENSIONAL ARRAYS:

import numpy as np
marks = np.array([
    [50, 60, 70],
    [80, 90, 100]
    ])
print(marks)


[50 60 70 80]
[[ 50  60  70]
 [ 80  90 100]]


In [ ]:
4. #IMORTANT ARRAY PROPERTIES:

import numpy as np
data = np.array([
    [50, 60, 70],
    [80, 90, 100]
    ])
print(data.shape)
print(data.ndim)
print(data.dtype)
print(data.size)


(2, 3)
2
int64
6


In [ ]:
5. #INDEXING:

import numpy as np
numbers = np.array([50, 60, 70, 80, 90, 100])
print(numbers[0])
print(numbers[2])

#NEGATIVE INDEXING:
print(numbers[-1])


50
70
100


In [ ]:
6. #INDEXING IN A 2D ARRAY:

import numpy as np
marks = np.array([
    [50, 60, 70],
    [80, 90, 100]
    ])
print(marks[0, 1])
print(marks[1, 2])

60
100


In [ ]:
7. #SLICING:

marks = np.array([50, 60, 70, 80, 90, 100])
print(marks[1:4])



[60 70 80]


In [ ]:
8. #VECTORIZED OPERATIONS:

import numpy as np
numbers = np.array([50, 60, 70, 80, 90, 100])
print(numbers + 5)
print(numbers * 2)
print(numbers - 5)
print(numbers / 2)


[ 55  65  75  85  95 105]
[100 120 140 160 180 200]
[45 55 65 75 85 95]
[25. 30. 35. 40. 45. 50.]


In [ ]:
9. #OPERATIONS BETWEEN TWO ARRAYS:

a = np.array([50, 60, 70])
b = np.array([80, 90, 100])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[130 150 170]
[-30 -30 -30]
[4000 5400 7000]
[0.625      0.66666667 0.7       ]


In [ ]:
10. #MATHEMATICAL FUNCTIONS:

std1_marks = np.array([50, 60, 70])
print(np.sqrt(std1_marks))
print(np.power(std1_marks, 2))
print(np.abs(std1_marks))
print(np.round(std1_marks))




[7.07106781 7.74596669 8.36660027]
[2500 3600 4900]
[50 60 70]
[50 60 70]


In [ ]:
11. #AGGREGIATE FUNCTIONS:

marks = np.array ([50, 60, 70, 80, 90, 100])
print(np.sum(marks))
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(np.median(marks))
print(np. std(marks))



450
75.0
100
50
75.0
17.07825127659933


In [ ]:
12. #CONDITION IN NUMPY:

marks = np.array ([50, 60, 70, 80, 90, 100])
print(marks >= 50)
print(marks[marks >= 50])
print(marks[marks <= 50])



[ True  True  True  True  True  True]
[ 50  60  70  80  90 100]
[50]


In [ ]:
13. #FILTERING DATA:

marks = np.array ([80, 75, 90, 45, 66, 78])
passed = marks[marks >= 50]
print(passed)
failed = marks[marks <= 50]
print(failed)

[80 75 90 66 78]
[45]


In [ ]:
14. #RESHAPE:

marks = np.array([50, 60, 70, 80, 90, 100])
new_array=numbers.reshape(2, 3)
print(new_array)

[[ 50  60  70]
 [ 80  90 100]]


In [ ]:
15. #FLATTEN:

data = np.array([
    [4, 5, 6],
    [7, 8, 9]
])
print(data.flatten())


[4 5 6 7 8 9]


In [ ]:
16.#USEFUL NUMPY FUNCTIONS:

print(np.zeros(7))
print(np.ones(6))
print(np.arange(1, 11))
print(np.arange(1, 11, 2))



[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [ ]:
17. #RANDOM NUMBERS:

marks = np.random.randint(65, 100, 35)
print(marks)

[75 97 65 82 74 66 98 69 67 73 68 72 94 79 80 76 87 68 70 81 80 67 67 98
 92 91 67 93 93 87 93 71 95 78 84]
